# Generated by Django 4.0.4 on 2022-06-08 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_note_options_remove_note_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='create_at',
            field=models.DateField(auto_now_add=True, verbose_name='Время создания'),
        ),
    ]
