# Generated by Django 4.0.4 on 2022-06-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_note_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
    ]
